import QueryProvider from "./QueryProvider";
import Header from "@/components/Header";

import "@/styles/globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Savers",
  description: "Generated by create next app",
};

const currentPagePath =
  typeof window !== "undefined" ? window.location.pathname : "";
const hideHeader = currentPagePath === "/"; // 헤더를 숨길 페이지의 경로

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {hideHeader ? null : <Header />}
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
